INSERT INTO puzzles (puzzle_id, puzzle, solution, solution_size, hint_one, award_points, comment) VALUES ('0000000001','The name of the insect which is of three letters', 'Ant', '4','Which is very small in size', '10','Hey dude, do it by end of this day....');
INSERT INTO puzzles (puzzle_id, puzzle, solution, solution_size, hint_one, award_points, comment) VALUES ('0000000002', 'This is the second puzzle', 'two', '3', 'The hint number two ','20', 'The second alpha numeric value');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points, comment) VALUES ('0000000003','This is puzzle three', 'three', 'The third alpha numeric value', '30', 'Do you know the answer');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points, comment) VALUES ('0000000004','This is puzzle four', 'four', 'The fourth alpha numeric value', '40', 'I dont know the answer');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points, comment) VALUES ('0000000005','This is puzzle five', 'five', 'The fifth alpha numeric value ', '50', 'I am not aware of this answer');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points, comment) VALUES ('0000000006','This is puzzle six', 'solution_six', 'The sixth hint', '60', 'Please give me small hint');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000007','This is puzzle Seven', 'seven', 'The seventh hint', '70');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000008','This puzzle number is eight', 'eight', 'Hint number nine', '80');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000009','The puzzle number is nine', 'nine', 'Hint number Nine', '90');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000010','The puzzle number is ten', 'ten', 'Hint number ten', '100');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000011','The puzzle number is eleven', 'eleven', 'Hint number eleven', '110');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000012','The puzzle number is twelve', 'twelve', 'Hint number twelve', '120');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000013','The puzzle number is thirteen', 'thirteen', 'Hint number thirteen', '130');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000014','The puzzle number is fourteen', 'fourteen', 'Hint number fourteen', '140');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000015','The puzzle number is fifteen', 'fifteen', 'Hint number is fifteen', '150');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000016','The puzzle number is sixteen', 'sixteen', 'Hint number is sixteen', '160');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000017','The puzzle number is seventeen', 'seventeen', 'Hint number is seventeen', '170');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000018','The puzzle number is eighteen', 'eighteen', 'Hint number is eighteen', '180');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000019','The puzzle number is nineteen', 'nineteen', 'Hint number is nineteen', '190');
INSERT INTO puzzles (puzzle_id, puzzle, solution, hint_one, award_points) VALUES ('0000000020','The puzzle number is twenty', 'twenty', 'Hint number is twenty', '200');
